AWSTemplateFormatVersion: "2010-09-09"
Description: An S3 bucket for ci/cd

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - staging
      - production
    Description: The environment to deploy to (dev, test, staging, production)

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "my-test-bucket-${Environment}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: updated the name of check the pull request
